config/routes.rb
MyBeans::Application.routes.draw do
  devise_for :users

  resources :beans

  root :to => 'beans#index'

end

app/models/bean.rb
class Bean < ActiveRecord::Base
	attr_default :lang, "ruby"
	def self.search(search, search2)
  		if search && search2
       		find(:all, :conditions => ['lang=? AND description LIKE ?', "#{search}","%#{search2}%"])
    	else
     		limit(0)
    	end
   	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :rememberable, 
  devise :database_authenticatable, :registerable,
          :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def authorize_blogger!
    if user_signed_in?
      return
    elsif user_signed_in?
      flash[:notice] = 'You must be an authorized user to do that'
      redirect_to :root
    else
      flash[:notice] = 'You need to sign in first'
      redirect_to new_user_session_path
    end
  end
end

app/controllers/beans_controller.rb
class BeansController < ApplicationController
  before_action :set_bean, only: [:show, :edit, :update, :destroy]
  before_filter :authorize_blogger!, :except => [:index, :show]


  
  # GET /beans
  # GET /beans.json
  def index
    @beans = Bean.order(:created_at).page(params[:page])

  end

  # GET /beans/1
  # GET /beans/1.json
  def show
  end

  # GET /beans/new
  def new
    @bean = Bean.new
  end

  # GET /beans/1/edit
  def edit
  end

  # GET /gists/show
  def search
     @beans = Bean.search(params[:lang],params[:desc])
     @beans = Kaminari.paginate_array(@beans).page(params[:page])
  end

  # POST /beans
  # POST /beans.json
  def create
    @bean = Bean.new(change_lang(bean_params))

    respond_to do |format|
      if @bean.save
        format.html { redirect_to @bean, notice: 'Bean was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bean }
      else
        format.html { render action: 'new' }
        format.json { render json: @bean.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beans/1
  # PATCH/PUT /beans/1.json
  def update
    respond_to do |format|
      if @bean.update(change_lang(bean_params))
        format.html { redirect_to @bean, notice: 'Bean was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bean.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beans/1
  # DELETE /beans/1.json
  def destroy
    @bean.destroy
    respond_to do |format|
      format.html { redirect_to beans_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bean
      @bean = Bean.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bean_params
      params.require(:bean).permit(:snippet, :lang, :description)
    end

    #Pygments validating lang
    def not_allowed?(lang)
      allowed = Pygments.lexers.flatten.select.with_index{|a,i| (i+1) % 2 == 0}
      allowed = allowed.map{|a| a[:aliases][0]}
      allowed = allowed.delete_if{|a| (/-cpp/ =~ a || /-objc/ =~ a)}
      allowed = allowed.sort

      good = false
      allowed.each do |l|

        if l == lang
          good = true
          break
        end

      end


      !good
    end

    def change_lang(gists)
     
      if not_allowed?(gists[:lang])
        gists[:lang] = "text"
      end

      return gists
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beans_helper.rb
module BeansHelper
end

app/views/beans/_bean.html.erb
 
      <tr class="post">
        <td ><%= raw Pygments.highlight(bean.snippet.length > 20 ? bean.snippet[0,20] + "..." : bean.snippet, lexer: bean.lang) %>
	<div class="visible-xs">
		<strong>Lang: </strong><br/>
		<%= bean.lang.length > 20 ? bean.lang[0,20] + "..." : bean.lang %>
		<br/>
		<strong>Description: </strong><br/> 
		<%= bean.description.length > 20 ? bean.description[0,20] + "..." : bean.description %>
		<br/>
		<%= link_to 'Show', bean, :class=>"btn btn-info" %>
        	<% if user_signed_in? then %><%= link_to 'Edit', edit_bean_path(bean), :class=>"btn btn-success" %>
        	<%= link_to 'Destroy', bean, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger" %><% end %>
	</div>
	</td>
        <td class="hidden-xs"><%= bean.lang %></td>
        <td class="hidden-xs"><%= bean.description %></td>
        <td><%= link_to 'Show', bean, :class=>"hidden-xs btn btn-info" %>
        <% if user_signed_in? then %><%= link_to 'Edit', edit_bean_path(bean), :class=>"hidden-xs btn btn-success" %>
        <%= link_to 'Destroy', bean, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"hidden-xs btn btn-danger" %><% end %></td>
      </tr>
   

app/views/beans/index.html.erb
<h1 >Listing beanaries</h1>

<%= link_to 'New Bean', new_bean_path, :class=>"btn btn-default" %>
<br/><br/>


<table class="table">
  <thead>
    <tr>
      <th>Snippet</th>
      <th class="hidden-xs">Lang</th>
      <th class="hidden-xs">Description</th>
      <th class="hidden-xs">Actions</th>

    </tr>
  </thead>

  <tbody class="page">

  <%= render @beans %>

  </tbody>

</table>

<%= paginate @beans %>




<div id="loader"></div>


<br>

app/views/beans/index.js.erb
$(".table").append("<tbody class='page'><%= escape_javascript(render(@posts)) %></tbody>");

app/views/beans/search.html.erb
<%
	allowed = Pygments.lexers.flatten.select.with_index{|a,i| (i+1) % 2 == 0}
	allowed = allowed.map{|a| a[:aliases][0]}
	allowed = allowed.delete_if{|a| (/-cpp/ =~ a || /-objc/ =~ a)}
	allowed = allowed.sort
%>

	<form role="search">
	      
	     
		<table class="findForm">
			<tr>
		  		<td>Lang:</td>
		  		<td><%= select_tag(:lang, options_for_select(allowed, params[:lang]))%></td>
		  	</tr>
			<tr>
		  		<td>
		  			Description:  &nbsp;
					
		  		</td>
				<td>
		  			<%= text_field_tag :desc, params[:desc], :class=>"desc" %><br>
		  		</td> 
			</tr>
	      </table>
	    
		
	      <br/>
	      <%= submit_tag "Search", :snippet => nil %>
	    
	</form>

	<!-- if we find some results -->
	<% if(@beans.length > 0) %>
	<h1>Results</h1>
	<hr/>

	<table class="table">
	  <thead>
	    <tr>
	      <th>Snippet</th>
	      <th class="hidden-xs">Lang</th>
	      <th class="hidden-xs">Description</th>
	      <th class="hidden-xs">Actions</th>
	    </tr>
	  </thead>

	   <tbody class="page">

	  <%= render @beans %>

	  </tbody>
	</table>
	<%= paginate @beans %>

	<div id="loader">
	</div>

	<% elsif(@beans.length == 0 && (params.has_key?(:lang) || params.has_key?(:desc))) %>
	<br/><br/><h3>No results found.</h3>
	<% end %>

app/views/beans/search.js.erb
$(".table").append("<tbody class='page'><%= escape_javascript(render(@posts)) %></tbody>");

app/views/common/_session.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">

		<%- if user_signed_in? %>

			<p class="navbar-text">Hello <%= current_user.email %></p><br />

			<%= link_to "Sign out".html_safe, destroy_user_session_path, :method => :delete, :class => "btn btn-default navbar-btn" %>
			<%= link_to "Home".html_safe, beans_path, :class => "btn btn-default navbar-btn" %>
			<%= link_to "Find".html_safe, beans_search_path, :class => "btn btn-default navbar-btn" %>

		<%- else %>
			<%= link_to "Home".html_safe, beans_path, :class => "btn btn-default navbar-btn" %>
			<%= link_to "Register".html_safe, new_user_registration_path, :class => "btn btn-default navbar-btn" %>
			<%= link_to "Sign in".html_safe, new_user_session_path, :class => "btn btn-default navbar-btn" %>
			<%= link_to "Find".html_safe, beans_search_path, :class => "btn btn-default navbar-btn" %>

		<%- end %>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBeanaries</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
</head>
<body>

    <%= render 'common/session' %>



<div class="pageContent">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
	<%= yield %>
</div>
</body>
</html>